# Site settings
title:          Too Old
description:    "A too old blog"
#baseurl:        "/tale"
url:            "https://ruishe.github.io"
baseurl:        ""
#url:            "https://www.tooold.cn"
#Google Analytics
google_analytics: UA-123385892-1

# Author
author:         
  name:         "Tooold"
  url:          
  email:        

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
